version: '3'
services:
  redis:
    container_name: redis_container
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  secure-chat:
    container_name: secure-chat-api
    image: secure-chat-api:latest
    env_file:
      - container.env
    ports:
      - 3000:3000

volumes:
  redis:
    driver: local

